from time import sleep
x = input("\033[1;32;40m Enter your name: \033")
def ga():
	
    print("\033[1;32;40m wishes \033")
    print('')
    
    
    print('')
    print('')
    print('  ღ♪*•.¸¸.•*¨¨*•.¸.•*¨¨*•.¸¸.•*•♪ღ♪')
    sleep(1)
    print('      ღ♪░H░A░P░P░Y░') 
    sleep(1)
    print('      B░I░R░T░H░D░A░Y░♪ღ')
    sleep(1)
    print('           '+x)
    sleep(1)
    print('  •♪ღ♪*•.¸¸.•*¨¨*••*¨¨*•.¸¸.•*•♪ღ♪')
    sleep(1)

    print('')
    print('')
    print('        ❦❦❦❦❦❦❦❦❦❦❦❦❦❦❦❦❦❦')
    sleep(1)
    print('')
    print('')
    print('            i i i i i i i')
    sleep(1)
    print('            i i i i i i i')
    sleep(1)
    print('            i i i i i i i')
    sleep(1)
    print('            i i i i i i i')
    sleep(1)
    print('         _____________________')
    sleep(1)
    print('        | ♥️  ❦  ♥️HAPPY♥️  ❦  ♥️ ||')
    sleep(1)
    print('      __                       __')
    sleep(1)
    print('     | ♥️ ♥️    ♥️BIRTHDAY♥️      ♥️ ♥|')
    sleep(1)
    print('   __	                          __')
    sleep(1)
    print('  | ♥️ ♥️   ♥️    ♥️TO YOU♥️     ♥️    ♥️ ♥|')

    print('  -----------------------------------')
    sleep(1)
    print('')
    print('')
    print('✨ ḪȁƿƿŸ 𝘉𝓲𝑟ᵵℏԂȁŸ ✨')
    sleep(1)
    print('')
    print('')
    print('May God bless you.......')
    sleep(1)
    print('')
    print('press r to see again and q to close program')
    
    b=input()
    if (b == 'r'):
    	ga()
print("\033[1;32;40m press any key to start.\033")
a = input()
if (a == 'q'):
	pass
else:
	ga()